# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ConfigParameterOverride(Model):
    """Information about a configuration parameter override.

    All required parameters must be populated in order to send to Azure.

    :param section_name: Required. Name of the section for the parameter
     override.
    :type section_name: str
    :param parameter_name: Required. Name of the parameter that has been
     overridden.
    :type parameter_name: str
    :param parameter_value: Required. Value of the overridden parameter.
    :type parameter_value: str
    :param timeout: The duration until config override is considered as valid.
    :type timeout: timedelta
    :param persist_across_upgrade: A value that indicates whether config
     override will be removed on upgrade or will still be considered as valid.
    :type persist_across_upgrade: bool
    """

    _validation = {
        'section_name': {'required': True},
        'parameter_name': {'required': True},
        'parameter_value': {'required': True},
    }

    _attribute_map = {
        'section_name': {'key': 'SectionName', 'type': 'str'},
        'parameter_name': {'key': 'ParameterName', 'type': 'str'},
        'parameter_value': {'key': 'ParameterValue', 'type': 'str'},
        'timeout': {'key': 'Timeout', 'type': 'duration'},
        'persist_across_upgrade': {'key': 'PersistAcrossUpgrade', 'type': 'bool'},
    }

    def __init__(self, *, section_name: str, parameter_name: str, parameter_value: str, timeout=None, persist_across_upgrade: bool=None, **kwargs) -> None:
        super(ConfigParameterOverride, self).__init__(**kwargs)
        self.section_name = section_name
        self.parameter_name = parameter_name
        self.parameter_value = parameter_value
        self.timeout = timeout
        self.persist_across_upgrade = persist_across_upgrade
