# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ApplicationUpdateDescription(Model):
    """Describes the parameters for updating an application instance.

    :param flags: Flags indicating whether other properties are set. Each of
     the associated properties corresponds to a flag, specified below, which,
     if set, indicate that the property is specified.
     If flags are not specified for a certain property, the property will not
     be updated even if the new value is provided.
     This property can be a combination of those flags obtained using bitwise
     'OR' operator. Exception is RemoveApplicationCapacity which cannot be
     specified along with other parameters.
     For example, if the provided value is 3 then the flags for MinimumNodes
     (1) and MaximumNodes (2) are set.
     - None - Does not indicate any other properties are set. The value is 0.
     - MinimumNodes - Indicates whether the MinimumNodes property is set. The
     value is 1.
     - MaximumNodes - Indicates whether the MinimumNodes property is set. The
     value is  2.
     - ApplicationMetrics - Indicates whether the ApplicationMetrics property
     is set. The value is 4.
    :type flags: str
    :param remove_application_capacity: Used to clear all parameters related
     to Application Capacity for this application. |
     It is not possible to specify this parameter together with other
     Application Capacity parameters. Default value: False .
    :type remove_application_capacity: bool
    :param minimum_nodes: The minimum number of nodes where Service Fabric
     will reserve capacity for this application. Note that this does not mean
     that the services of this application will be placed on all of those
     nodes. If this property is set to zero, no capacity will be reserved. The
     value of this property cannot be more than the value of the MaximumNodes
     property.
    :type minimum_nodes: long
    :param maximum_nodes: The maximum number of nodes where Service Fabric
     will reserve capacity for this application. Note that this does not mean
     that the services of this application will be placed on all of those
     nodes. By default, the value of this property is zero and it means that
     the services can be placed on any node. Default value: 0 .
    :type maximum_nodes: long
    :param application_metrics: List of application capacity metric
     description.
    :type application_metrics:
     list[~azure.servicefabric.models.ApplicationMetricDescription]
    """

    _validation = {
        'minimum_nodes': {'minimum': 0},
        'maximum_nodes': {'minimum': 0},
    }

    _attribute_map = {
        'flags': {'key': 'Flags', 'type': 'str'},
        'remove_application_capacity': {'key': 'RemoveApplicationCapacity', 'type': 'bool'},
        'minimum_nodes': {'key': 'MinimumNodes', 'type': 'long'},
        'maximum_nodes': {'key': 'MaximumNodes', 'type': 'long'},
        'application_metrics': {'key': 'ApplicationMetrics', 'type': '[ApplicationMetricDescription]'},
    }

    def __init__(self, *, flags: str=None, remove_application_capacity: bool=False, minimum_nodes: int=None, maximum_nodes: int=0, application_metrics=None, **kwargs) -> None:
        super(ApplicationUpdateDescription, self).__init__(**kwargs)
        self.flags = flags
        self.remove_application_capacity = remove_application_capacity
        self.minimum_nodes = minimum_nodes
        self.maximum_nodes = maximum_nodes
        self.application_metrics = application_metrics
