# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DiskInfo(Model):
    """Information about the disk.

    :param capacity: the disk size in bytes
    :type capacity: str
    :param available_space: the available disk space in bytes
    :type available_space: str
    """

    _attribute_map = {
        'capacity': {'key': 'Capacity', 'type': 'str'},
        'available_space': {'key': 'AvailableSpace', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(DiskInfo, self).__init__(**kwargs)
        self.capacity = kwargs.get('capacity', None)
        self.available_space = kwargs.get('available_space', None)
