# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EnableBackupDescription(Model):
    """Specifies the parameters needed to enable periodic backup.

    :param backup_policy_name: Name of the backup policy to be used for
     enabling periodic backups.
    :type backup_policy_name: str
    """

    _validation = {
        'backup_policy_name': {'required': True},
    }

    _attribute_map = {
        'backup_policy_name': {'key': 'BackupPolicyName', 'type': 'str'},
    }

    def __init__(self, backup_policy_name):
        super(EnableBackupDescription, self).__init__()
        self.backup_policy_name = backup_policy_name
