# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FolderSizeInfo(Model):
    """Information of a image store folder size.

    :param store_relative_path: The remote location within image store. This
     path is relative to the image store root.
    :type store_relative_path: str
    :param folder_size: The size of folder in bytes.
    :type folder_size: str
    """

    _attribute_map = {
        'store_relative_path': {'key': 'StoreRelativePath', 'type': 'str'},
        'folder_size': {'key': 'FolderSize', 'type': 'str'},
    }

    def __init__(self, *, store_relative_path: str=None, folder_size: str=None, **kwargs) -> None:
        super(FolderSizeInfo, self).__init__(**kwargs)
        self.store_relative_path = store_relative_path
        self.folder_size = folder_size
