# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class InstanceLifecycleDescription(Model):
    """Describes how the instance will behave.

    :param restore_replica_location_after_upgrade: If set to true, move/swap
     replica to original location after upgrade.
    :type restore_replica_location_after_upgrade: bool
    """

    _attribute_map = {
        'restore_replica_location_after_upgrade': {'key': 'RestoreReplicaLocationAfterUpgrade', 'type': 'bool'},
    }

    def __init__(self, **kwargs):
        super(InstanceLifecycleDescription, self).__init__(**kwargs)
        self.restore_replica_location_after_upgrade = kwargs.get('restore_replica_location_after_upgrade', None)
