# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NodeUpgradeProgressInfo(Model):
    """Information about the upgrading node and its status.

    :param node_name: The name of a Service Fabric node.
    :type node_name: str
    :param upgrade_phase: The state of the upgrading node. Possible values
     include: 'Invalid', 'PreUpgradeSafetyCheck', 'Upgrading',
     'PostUpgradeSafetyCheck'
    :type upgrade_phase: str or ~azure.servicefabric.models.NodeUpgradePhase
    :param pending_safety_checks: List of pending safety checks
    :type pending_safety_checks:
     list[~azure.servicefabric.models.SafetyCheckWrapper]
    :param upgrade_duration: The estimated time spent processing the node
     since it was deactivated during a node-by-node upgrade.
    :type upgrade_duration: str
    """

    _attribute_map = {
        'node_name': {'key': 'NodeName', 'type': 'str'},
        'upgrade_phase': {'key': 'UpgradePhase', 'type': 'str'},
        'pending_safety_checks': {'key': 'PendingSafetyChecks', 'type': '[SafetyCheckWrapper]'},
        'upgrade_duration': {'key': 'UpgradeDuration', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(NodeUpgradeProgressInfo, self).__init__(**kwargs)
        self.node_name = kwargs.get('node_name', None)
        self.upgrade_phase = kwargs.get('upgrade_phase', None)
        self.pending_safety_checks = kwargs.get('pending_safety_checks', None)
        self.upgrade_duration = kwargs.get('upgrade_duration', None)
