# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SecretResourceValue(Model):
    """SecretResourceValue.

    :param content_type: The type of the secret value. Currently this value is
     opaque to Service Fabric.
    :type content_type: str
    :param value: The value of the secret resource. When creating or updating
     the resource, value is required. Once created, the value can be retrieved
     using an explicit operation against the resource.
    :type value: str
    :param version: The version of the secret value. If must be unique and
     different for different value. A same version cannot have different value.
    :type version: str
    """

    _attribute_map = {
        'content_type': {'key': 'contentType', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
    }

    def __init__(self, content_type=None, value=None, version=None):
        super(SecretResourceValue, self).__init__()
        self.content_type = content_type
        self.value = value
        self.version = version
