# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ServiceUpgradeProgress(Model):
    """Information about how many replicas are completed or pending for a specific
    service during upgrade.

    :param service_name: Name of the Service resource.
    :type service_name: str
    :param completed_replica_count: The number of replicas that completes the
     upgrade in the service.
    :type completed_replica_count: str
    :param pending_replica_count: The number of replicas that are waiting to
     be upgraded in the service.
    :type pending_replica_count: str
    """

    _attribute_map = {
        'service_name': {'key': 'ServiceName', 'type': 'str'},
        'completed_replica_count': {'key': 'CompletedReplicaCount', 'type': 'str'},
        'pending_replica_count': {'key': 'PendingReplicaCount', 'type': 'str'},
    }

    def __init__(self, *, service_name: str=None, completed_replica_count: str=None, pending_replica_count: str=None, **kwargs) -> None:
        super(ServiceUpgradeProgress, self).__init__(**kwargs)
        self.service_name = service_name
        self.completed_replica_count = completed_replica_count
        self.pending_replica_count = pending_replica_count
