# -----------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
# -----------------------------------------------------------------------------

"""Help documentation for Service Fabric health commands."""

from knack.help_files import helps

helps['cluster report-health'] = """
    type: command
    short-summary: Sends a health report on the Service Fabric cluster.
    long-summary: The report must contain the information about the source of
        the health report and property on which it is reported. The report is
        sent to a Service Fabric gateway node, which forwards to the health
        store. The report may be accepted by the gateway, but rejected by the
        health store after extra validation. For example, the health store may
        reject the report because of an invalid parameter, like a stale
        sequence number. To see whether the report was applied in the health
        store, check that the report appears in the HealthEvents of the
        cluster.
    parameters:
        - name: --source-id
          type: string
          short-summary: The source name which identifies the
            client/watchdog/system component which generated the health
            information.
        - name: --health-property
          type: string
          short-summary: The property of the health information.
          long-summary: An entity can have health reports for different
            properties. The property is a string and not a fixed enumeration to
            allow the reporter flexibility to categorize the state condition that
            triggers the report. For example, a reporter with SourceId
            "LocalWatchdog" can monitor the state of the available disk on a
            node, so it can report "AvailableDisk" property on that node. The
            same reporter can monitor the node connectivity, so it can report a
            property "Connectivity" on the same node. In the health store,
            these reports are treated as separate health events for the
            specified node. Together with the SourceId, the property uniquely
            identifies the health information.
        - name: --health-state
          type: string
          short-summary: "Possible values include: 'Invalid', 'Ok', 'Warning',
            'Error', 'Unknown'"
        - name: --ttl
          type: string
          short-summary: The duration for which this health report is valid.
            This field is using ISO8601 format for specifying the duration.
          long-summary: When clients report periodically, they should send
            reports with higher frequency than time to live. If clients report
            on transition, they can set the time to live to infinite. When
            time to live expires, the health event that contains the health
            information is either removed from health store, if
            RemoveWhenExpired is true, or evaluated at error, if
            RemoveWhenExpired false. If not specified, time to live defaults
            to infinite value.
        - name: --description
          type: string
          short-summary: The description of the health information.
          long-summary: It represents free text used to add human readable
            information about the report. The maximum string length for the
            description is 4096 characters. If the provided string is longer,
            it will be automatically truncated. When truncated, the last
            characters of the description contain a marker "[Truncated]", and
            total string size is 4096 characters. The presence of the marker
            indicates to users that truncation occurred. Note that when
            truncated, the description has less than 4096 characters from the
            original string.
        - name: --sequence-number
          type: string
          short-summary: The sequence number for this health report as a
            numeric string.
          long-summary: The report sequence number is used by the health store
            to detect stale reports. If not specified, a sequence number is
            auto-generated by the health client when a report is added.
        - name: --remove-when-expired
          type: bool
          short-summary: Value that indicates whether the report is removed
            from health store when it expires.
          long-summary: If set to true, the report is removed from the health
            store after it expires. If set to false, the report is treated as
            an error when expired. The value of this property is false by
            default. When clients report periodically, they should set
            RemoveWhenExpired false (default). This way, is the reporter has
            issues (e.g. deadlock) and can't report, the entity is evaluated at
            error when the health report expires. This flags the entity as
            being in Error health state.
        - name: --immediate
          type: bool
          short-summary: A flag which indicates whether the report should be
            sent immediately.
          long-summary: A health report is sent to a Service Fabric gateway
            Application, which forwards to the health store. If Immediate is
            set to true, the report is sent immediately from HTTP Gateway to
            the health store, regardless of the fabric client settings that
            the HTTP Gateway Application is using. This is useful for critical
            reports that should be sent as soon as possible. Depending on
            timing and other conditions, sending the report may still fail,
            for example if the HTTP Gateway is closed or the message doesn't
            reach the Gateway. If Immediate is set to false, the report is sent
            based on the health client settings from the HTTP Gateway.
            Therefore, it will be batched according to the
            HealthReportSendInterval configuration. This is the recommended
            setting because it allows the health client to optimize health
            reporting messages to health store as well as health report
            processing. By default, reports are not sent immediately.
"""

helps['node report-health'] = """
    type: command
    short-summary: Sends a health report on the Service Fabric node.
    long-summary: Reports health state of the specified Service Fabric node.
        The report must contain the information about the source of the health
        report and property on which it is reported. The report is sent to a
        Service Fabric gateway node, which forwards to the health store. The
        report may be accepted by the gateway, but rejected by the health store
        after extra validation. For example, the health store may reject the
        report because of an invalid parameter, like a stale sequence number.
        To see whether the report was applied in the health store, check that
        the report appears in the HealthEvents section.
    parameters:
        - name: --node-name
          type: string
          short-summary: Node name to report on
        - name: --source-id
          type: string
          short-summary: The source name which identifies the
            client/watchdog/system component which generated the health
            information.
        - name: --health-property
          type: string
          short-summary: The property of the health information.
          long-summary: An entity can have health reports for different
            properties. The property is a string and not a fixed enumeration to
            allow the reporter flexibility to categorize the state condition that
            triggers the report. For example, a reporter with SourceId
            "LocalWatchdog" can monitor the state of the available disk on a
            node, so it can report "AvailableDisk" property on that node. The
            same reporter can monitor the node connectivity, so it can report a
            property "Connectivity" on the same node. In the health store,
            these reports are treated as separate health events for the
            specified node. Together with the SourceId, the property uniquely
            identifies the health information.
        - name: --health-state
          type: string
          short-summary: "Possible values include: 'Invalid', 'Ok', 'Warning',
            'Error', 'Unknown'"
        - name: --ttl
          type: string
          short-summary: The duration for which this health report is valid.
            This field is using ISO8601 format for specifying the duration.
          long-summary: When clients report periodically, they should send
            reports with higher frequency than time to live. If clients report
            on transition, they can set the time to live to infinite. When
            time to live expires, the health event that contains the health
            information is either removed from health store, if
            RemoveWhenExpired is true, or evaluated at error, if
            RemoveWhenExpired false. If not specified, time to live defaults
            to infinite value.
        - name: --description
          type: string
          short-summary: The description of the health information.
          long-summary: It represents free text used to add human readable
            information about the report. The maximum string length for the
            description is 4096 characters. If the provided string is longer,
            it will be automatically truncated. When truncated, the last
            characters of the description contain a marker "[Truncated]", and
            total string size is 4096 characters. The presence of the marker
            indicates to users that truncation occurred. Note that when
            truncated, the description has less than 4096 characters from the
            original string.
        - name: --sequence-number
          type: string
          short-summary: The sequence number for this health report as a
            numeric string.
          long-summary: The report sequence number is used by the health store
            to detect stale reports. If not specified, a sequence number is
            auto-generated by the health client when a report is added.
        - name: --remove-when-expired
          type: bool
          short-summary: Value that indicates whether the report is removed
            from health store when it expires.
          long-summary: If set to true, the report is removed from the health
            store after it expires. If set to false, the report is treated as
            an error when expired. The value of this property is false by
            default. When clients report periodically, they should set
            RemoveWhenExpired false (default). This way, is the reporter has
            issues (e.g. deadlock) and can't report, the entity is evaluated at
            error when the health report expires. This flags the entity as
            being in Error health state.
        - name: --immediate
          type: bool
          short-summary: A flag which indicates whether the report should be
            sent immediately.
          long-summary: A health report is sent to a Service Fabric gateway
            Application, which forwards to the health store. If Immediate is
            set to true, the report is sent immediately from HTTP Gateway to
            the health store, regardless of the fabric client settings that
            the HTTP Gateway Application is using. This is useful for critical
            reports that should be sent as soon as possible. Depending on
            timing and other conditions, sending the report may still fail,
            for example if the HTTP Gateway is closed or the message doesn't
            reach the Gateway. If Immediate is set to false, the report is sent
            based on the health client settings from the HTTP Gateway.
            Therefore, it will be batched according to the
            HealthReportSendInterval configuration. This is the recommended
            setting because it allows the health client to optimize health
            reporting messages to health store as well as health report
            processing. By default, reports are not sent immediately.
"""

helps['application report-health'] = """
    type: command
    short-summary: Sends a health report on the Service Fabric application
    long-summary: Reports health state of the specified Service Fabric
        application. The report must contain the information about the source
        of the health report and property on which it is reported.
        The report is sent to a Service Fabric gateway Application, which
        forwards to the health store. The report may be accepted by the
        gateway, but rejected by the health store after extra validation.
        For example, the health store may reject the report because of an
        invalid parameter, like a stale sequence number. To see whether the
        report was applied in the health store, get application health and
        check that the report appears.
    parameters:
        - name: --application-id
          type: string
          short-summary: The identity of the application
          long-summary: "This is typically the full name of the application
            without the 'fabric:' URI scheme. Starting from version 6.0,
            hierarchical names are delimited with the '~' character. For
            example, if the application name is 'fabric:/myapp/app1', the
            application identity would be 'myapp~app1' in 6.0+ and 'myapp/app1'
            in previous versions."
        - name: --source-id
          type: string
          short-summary: The source name which identifies the
            client/watchdog/system component which generated the health
            information.
        - name: --health-property
          type: string
          short-summary: The property of the health information.
          long-summary: An entity can have health reports for different
            properties. The property is a string and not a fixed enumeration to
            allow the reporter flexibility to categorize the state condition that
            triggers the report. For example, a reporter with SourceId
            "LocalWatchdog" can monitor the state of the available disk on a
            node, so it can report "AvailableDisk" property on that node. The
            same reporter can monitor the node connectivity, so it can report a
            property "Connectivity" on the same node. In the health store,
            these reports are treated as separate health events for the
            specified node. Together with the SourceId, the property uniquely
            identifies the health information.
        - name: --health-state
          type: string
          short-summary: "Possible values include: 'Invalid', 'Ok', 'Warning',
            'Error', 'Unknown'"
        - name: --ttl
          type: string
          short-summary: The duration for which this health report is valid.
            This field is using ISO8601 format for specifying the duration.
          long-summary: When clients report periodically, they should send
            reports with higher frequency than time to live. If clients report
            on transition, they can set the time to live to infinite. When
            time to live expires, the health event that contains the health
            information is either removed from health store, if
            RemoveWhenExpired is true, or evaluated at error, if
            RemoveWhenExpired false. If not specified, time to live defaults
            to infinite value.
        - name: --description
          type: string
          short-summary: The description of the health information.
          long-summary: It represents free text used to add human readable
            information about the report. The maximum string length for the
            description is 4096 characters. If the provided string is longer,
            it will be automatically truncated. When truncated, the last
            characters of the description contain a marker "[Truncated]", and
            total string size is 4096 characters. The presence of the marker
            indicates to users that truncation occurred. Note that when
            truncated, the description has less than 4096 characters from the
            original string.
        - name: --sequence-number
          type: string
          short-summary: The sequence number for this health report as a
            numeric string.
          long-summary: The report sequence number is used by the health store
            to detect stale reports. If not specified, a sequence number is
            auto-generated by the health client when a report is added.
        - name: --remove-when-expired
          type: bool
          short-summary: Value that indicates whether the report is removed
            from health store when it expires.
          long-summary: If set to true, the report is removed from the health
            store after it expires. If set to false, the report is treated as
            an error when expired. The value of this property is false by
            default. When clients report periodically, they should set
            RemoveWhenExpired false (default). This way, is the reporter has
            issues (e.g. deadlock) and can't report, the entity is evaluated at
            error when the health report expires. This flags the entity as
            being in Error health state.
        - name: --immediate
          type: bool
          short-summary: A flag which indicates whether the report should be
            sent immediately.
          long-summary: A health report is sent to a Service Fabric gateway
            Application, which forwards to the health store. If Immediate is
            set to true, the report is sent immediately from HTTP Gateway to
            the health store, regardless of the fabric client settings that
            the HTTP Gateway Application is using. This is useful for critical
            reports that should be sent as soon as possible. Depending on
            timing and other conditions, sending the report may still fail,
            for example if the HTTP Gateway is closed or the message doesn't
            reach the Gateway. If Immediate is set to false, the report is sent
            based on the health client settings from the HTTP Gateway.
            Therefore, it will be batched according to the
            HealthReportSendInterval configuration. This is the recommended
            setting because it allows the health client to optimize health
            reporting messages to health store as well as health report
            processing. By default, reports are not sent immediately.
"""

helps['service report-health'] = """
    type: command
    short-summary: Sends a health report on the Service Fabric service
    long-summary: Reports health state of the specified Service Fabric service.
      The report must contain the information about the source of the health
      report and property on which it is reported. The report is sent to a
      Service Fabric gateway Service, which forwards to the health store.
      The report may be accepted by the gateway, but rejected by the health
      store after extra validation. For example, the health store may reject
      the report because of an invalid parameter, like a stale sequence number.
      To see whether the report was applied in the health store, check that the
      report appears in the health events of the service.
    parameters:
        - name: --service-id
          type: string
          short-summary: The identity of the service.
          long-summary: "This is typically the full name of the service without
            the 'fabric:' URI scheme. Starting from version 6.0, hierarchical
            names are delimited with the '~' character. For example, if the
            service name is 'fabric:/myapp/app1/svc1', the service identity
            would be 'myapp~app1~svc1' in 6.0+ and 'myapp/app1/svc1' in
            previous versions."
        - name: --source-id
          type: string
          short-summary: The source name which identifies the
            client/watchdog/system component which generated the health
            information.
        - name: --health-property
          type: string
          short-summary: The property of the health information.
          long-summary: An entity can have health reports for different
            properties. The property is a string and not a fixed enumeration to
            allow the reporter flexibility to categorize the state condition that
            triggers the report. For example, a reporter with SourceId
            "LocalWatchdog" can monitor the state of the available disk on a
            node, so it can report "AvailableDisk" property on that node. The
            same reporter can monitor the node connectivity, so it can report a
            property "Connectivity" on the same node. In the health store,
            these reports are treated as separate health events for the
            specified node. Together with the SourceId, the property uniquely
            identifies the health information.
        - name: --health-state
          type: string
          short-summary: "Possible values include: 'Invalid', 'Ok', 'Warning',
            'Error', 'Unknown'"
        - name: --ttl
          type: string
          short-summary: The duration for which this health report is valid.
            This field is using ISO8601 format for specifying the duration.
          long-summary: When clients report periodically, they should send
            reports with higher frequency than time to live. If clients report
            on transition, they can set the time to live to infinite. When
            time to live expires, the health event that contains the health
            information is either removed from health store, if
            RemoveWhenExpired is true, or evaluated at error, if
            RemoveWhenExpired false. If not specified, time to live defaults
            to infinite value.
        - name: --description
          type: string
          short-summary: The description of the health information.
          long-summary: It represents free text used to add human readable
            information about the report. The maximum string length for the
            description is 4096 characters. If the provided string is longer,
            it will be automatically truncated. When truncated, the last
            characters of the description contain a marker "[Truncated]", and
            total string size is 4096 characters. The presence of the marker
            indicates to users that truncation occurred. Note that when
            truncated, the description has less than 4096 characters from the
            original string.
        - name: --sequence-number
          type: string
          short-summary: The sequence number for this health report as a
            numeric string.
          long-summary: The report sequence number is used by the health store
            to detect stale reports. If not specified, a sequence number is
            auto-generated by the health client when a report is added.
        - name: --remove-when-expired
          type: bool
          short-summary: Value that indicates whether the report is removed
            from health store when it expires.
          long-summary: If set to true, the report is removed from the health
            store after it expires. If set to false, the report is treated as
            an error when expired. The value of this property is false by
            default. When clients report periodically, they should set
            RemoveWhenExpired false (default). This way, is the reporter has
            issues (e.g. deadlock) and can't report, the entity is evaluated at
            error when the health report expires. This flags the entity as
            being in Error health state.
        - name: --immediate
          type: bool
          short-summary: A flag which indicates whether the report should be
            sent immediately.
          long-summary: A health report is sent to a Service Fabric gateway
            Application, which forwards to the health store. If Immediate is
            set to true, the report is sent immediately from HTTP Gateway to
            the health store, regardless of the fabric client settings that
            the HTTP Gateway Application is using. This is useful for critical
            reports that should be sent as soon as possible. Depending on
            timing and other conditions, sending the report may still fail,
            for example if the HTTP Gateway is closed or the message doesn't
            reach the Gateway. If Immediate is set to false, the report is sent
            based on the health client settings from the HTTP Gateway.
            Therefore, it will be batched according to the
            HealthReportSendInterval configuration. This is the recommended
            setting because it allows the health client to optimize health
            reporting messages to health store as well as health report
            processing. By default, reports are not sent immediately.
"""

helps['partition report-health'] = """
    type: command
    short-summary: Sends a health report on the Service Fabric partition.
    long-summary: Reports health state of the specified Service Fabric
        partition. The report must contain the information about the source of
        the health report and property on which it is reported. The report is
        sent to a Service Fabric gateway Partition, which forwards to the
        health store. The report may be accepted by the gateway, but rejected
        by the health store after extra validation. For example, the health
        store may reject the report because of an invalid parameter, like a
        stale sequence number. To see whether the report was applied in the
        health store, check that the report appears in the events section.
    parameters:
        - name: --partition-id
          type: string
          short-summary: The identity of the partition
        - name: --source-id
          type: string
          short-summary: The source name which identifies the
            client/watchdog/system component which generated the health
            information.
        - name: --health-property
          type: string
          short-summary: The property of the health information.
          long-summary: An entity can have health reports for different
            properties. The property is a string and not a fixed enumeration to
            allow the reporter flexibility to categorize the state condition that
            triggers the report. For example, a reporter with SourceId
            "LocalWatchdog" can monitor the state of the available disk on a
            node, so it can report "AvailableDisk" property on that node. The
            same reporter can monitor the node connectivity, so it can report a
            property "Connectivity" on the same node. In the health store,
            these reports are treated as separate health events for the
            specified node. Together with the SourceId, the property uniquely
            identifies the health information.
        - name: --health-state
          type: string
          short-summary: "Possible values include: 'Invalid', 'Ok', 'Warning',
            'Error', 'Unknown'"
        - name: --ttl
          type: string
          short-summary: The duration for which this health report is valid.
            This field is using ISO8601 format for specifying the duration.
          long-summary: When clients report periodically, they should send
            reports with higher frequency than time to live. If clients report
            on transition, they can set the time to live to infinite. When
            time to live expires, the health event that contains the health
            information is either removed from health store, if
            RemoveWhenExpired is true, or evaluated at error, if
            RemoveWhenExpired false. If not specified, time to live defaults
            to infinite value.
        - name: --description
          type: string
          short-summary: The description of the health information.
          long-summary: It represents free text used to add human readable
            information about the report. The maximum string length for the
            description is 4096 characters. If the provided string is longer,
            it will be automatically truncated. When truncated, the last
            characters of the description contain a marker "[Truncated]", and
            total string size is 4096 characters. The presence of the marker
            indicates to users that truncation occurred. Note that when
            truncated, the description has less than 4096 characters from the
            original string.
        - name: --sequence-number
          type: string
          short-summary: The sequence number for this health report as a
            numeric string.
          long-summary: The report sequence number is used by the health store
            to detect stale reports. If not specified, a sequence number is
            auto-generated by the health client when a report is added.
        - name: --remove-when-expired
          type: bool
          short-summary: Value that indicates whether the report is removed
            from health store when it expires.
          long-summary: If set to true, the report is removed from the health
            store after it expires. If set to false, the report is treated as
            an error when expired. The value of this property is false by
            default. When clients report periodically, they should set
            RemoveWhenExpired false (default). This way, is the reporter has
            issues (e.g. deadlock) and can't report, the entity is evaluated at
            error when the health report expires. This flags the entity as
            being in Error health state.
        - name: --immediate
          type: bool
          short-summary: A flag which indicates whether the report should be
            sent immediately.
          long-summary: A health report is sent to a Service Fabric gateway
            Application, which forwards to the health store. If Immediate is
            set to true, the report is sent immediately from HTTP Gateway to
            the health store, regardless of the fabric client settings that
            the HTTP Gateway Application is using. This is useful for critical
            reports that should be sent as soon as possible. Depending on
            timing and other conditions, sending the report may still fail,
            for example if the HTTP Gateway is closed or the message doesn't
            reach the Gateway. If Immediate is set to false, the report is sent
            based on the health client settings from the HTTP Gateway.
            Therefore, it will be batched according to the
            HealthReportSendInterval configuration. This is the recommended
            setting because it allows the health client to optimize health
            reporting messages to health store as well as health report
            processing. By default, reports are not sent immediately.
"""

helps['replica report-health'] = """
    type: command
    short-summary: Sends a health report on the Service Fabric replica
    long-summary: Reports health state of the specified Service Fabric replica.
        The report must contain the information about the source of the health
        report and property on which it is reported. The report is sent to a
        Service Fabric gateway Replica, which forwards to the health store. The
        report may be accepted by the gateway, but rejected by the health store
        after extra validation. For example, the health store may reject the
        report because of an invalid parameter, like a stale sequence number.
        To see whether the report was applied in the health store, check that
        the report appears in the events section.
    parameters:
        - name: --partition-id
          type: string
          short-summary: The identity of the partition
        - name: --replica-id
          type: string
          short-summary: The identity of the partition
        - name: --service-kind
          type: string
          short-summary: "The kind of service replica (stateless or stateful)
            for which the health is being reported. Following are the possible
            values: 'Stateless', 'Stateful'."
        - name: --source-id
          type: string
          short-summary: The source name which identifies the
            client/watchdog/system component which generated the health
            information.
        - name: --health-property
          type: string
          short-summary: The property of the health information.
          long-summary: An entity can have health reports for different
            properties. The property is a string and not a fixed enumeration to
            allow the reporter flexibility to categorize the state condition that
            triggers the report. For example, a reporter with SourceId
            "LocalWatchdog" can monitor the state of the available disk on a
            node, so it can report "AvailableDisk" property on that node. The
            same reporter can monitor the node connectivity, so it can report a
            property "Connectivity" on the same node. In the health store,
            these reports are treated as separate health events for the
            specified node. Together with the SourceId, the property uniquely
            identifies the health information.
        - name: --health-state
          type: string
          short-summary: "Possible values include: 'Invalid', 'Ok', 'Warning',
            'Error', 'Unknown'"
        - name: --ttl
          type: string
          short-summary: The duration for which this health report is valid.
            This field is using ISO8601 format for specifying the duration.
          long-summary: When clients report periodically, they should send
            reports with higher frequency than time to live. If clients report
            on transition, they can set the time to live to infinite. When
            time to live expires, the health event that contains the health
            information is either removed from health store, if
            RemoveWhenExpired is true, or evaluated at error, if
            RemoveWhenExpired false. If not specified, time to live defaults
            to infinite value.
        - name: --description
          type: string
          short-summary: The description of the health information.
          long-summary: It represents free text used to add human readable
            information about the report. The maximum string length for the
            description is 4096 characters. If the provided string is longer,
            it will be automatically truncated. When truncated, the last
            characters of the description contain a marker "[Truncated]", and
            total string size is 4096 characters. The presence of the marker
            indicates to users that truncation occurred. Note that when
            truncated, the description has less than 4096 characters from the
            original string.
        - name: --sequence-number
          type: string
          short-summary: The sequence number for this health report as a
            numeric string.
          long-summary: The report sequence number is used by the health store
            to detect stale reports. If not specified, a sequence number is
            auto-generated by the health client when a report is added.
        - name: --remove-when-expired
          type: bool
          short-summary: Value that indicates whether the report is removed
            from health store when it expires.
          long-summary: If set to true, the report is removed from the health
            store after it expires. If set to false, the report is treated as
            an error when expired. The value of this property is false by
            default. When clients report periodically, they should set
            RemoveWhenExpired false (default). This way, is the reporter has
            issues (e.g. deadlock) and can't report, the entity is evaluated at
            error when the health report expires. This flags the entity as
            being in Error health state.
        - name: --immediate
          type: bool
          short-summary: A flag which indicates whether the report should be
            sent immediately.
          long-summary: A health report is sent to a Service Fabric gateway
            Application, which forwards to the health store. If Immediate is
            set to true, the report is sent immediately from HTTP Gateway to
            the health store, regardless of the fabric client settings that
            the HTTP Gateway Application is using. This is useful for critical
            reports that should be sent as soon as possible. Depending on
            timing and other conditions, sending the report may still fail,
            for example if the HTTP Gateway is closed or the message doesn't
            reach the Gateway. If Immediate is set to false, the report is sent
            based on the health client settings from the HTTP Gateway.
            Therefore, it will be batched according to the
            HealthReportSendInterval configuration. This is the recommended
            setting because it allows the health client to optimize health
            reporting messages to health store as well as health report
            processing. By default, reports are not sent immediately.
"""
