# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NodeTypeHealthPolicyMapItem(Model):
    """Defines an item in NodeTypeHealthPolicyMap.

    All required parameters must be populated in order to send to Azure.

    :param key: Required. The key of the node type health policy map item.
     This is the name of the node type.
    :type key: str
    :param value: Required. The value of the node type health policy map item.
     If the percentage is respected but there is at least one unhealthy node in
     the node type, the health is evaluated as Warning.
     The percentage is calculated by dividing the number of unhealthy nodes
     over the total number of nodes in the node type.
     The computation rounds up to tolerate one failure on small numbers of
     nodes.
     The max percent unhealthy nodes allowed for the node type. Must be between
     zero and 100.
    :type value: int
    """

    _validation = {
        'key': {'required': True},
        'value': {'required': True},
    }

    _attribute_map = {
        'key': {'key': 'Key', 'type': 'str'},
        'value': {'key': 'Value', 'type': 'int'},
    }

    def __init__(self, *, key: str, value: int, **kwargs) -> None:
        super(NodeTypeHealthPolicyMapItem, self).__init__(**kwargs)
        self.key = key
        self.value = value
