# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ServiceIdentity(Model):
    """Map service identity friendly name to an application identity.

    :param name: The identity friendly name.
    :type name: str
    :param identity_ref: The application identity name.
    :type identity_ref: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'identity_ref': {'key': 'identityRef', 'type': 'str'},
    }

    def __init__(self, *, name: str=None, identity_ref: str=None, **kwargs) -> None:
        super(ServiceIdentity, self).__init__(**kwargs)
        self.name = name
        self.identity_ref = identity_ref
