# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._operations import ServiceFabricClientAPIsOperationsMixin
from ._operations import MeshSecretOperations
from ._operations import MeshSecretValueOperations
from ._operations import MeshVolumeOperations
from ._operations import MeshNetworkOperations
from ._operations import MeshApplicationOperations
from ._operations import MeshServiceOperations
from ._operations import MeshCodePackageOperations
from ._operations import MeshServiceReplicaOperations
from ._operations import MeshGatewayOperations

from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk
__all__ = [
    'ServiceFabricClientAPIsOperationsMixin',
    'MeshSecretOperations',
    'MeshSecretValueOperations',
    'MeshVolumeOperations',
    'MeshNetworkOperations',
    'MeshApplicationOperations',
    'MeshServiceOperations',
    'MeshCodePackageOperations',
    'MeshServiceReplicaOperations',
    'MeshGatewayOperations',
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()