# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .get_operations import GetOperations
from .post_operations import PostOperations
from .put_operations import PutOperations
from .delete_operations import DeleteOperations

__all__ = [
    'GetOperations',
    'PostOperations',
    'PutOperations',
    'DeleteOperations',
]
