application:
  schemaVersion: 1.0.0
  name: ApplicationName
  properties:  
    services:
      - name: FabricServiceName
        description: FabricServiceName description.
        osType: OsTypeValue
        codePackages:
          - name: FabricServiceName
            image: FabricServiceImage
            endpoints:
              - name: FabricServiceListener
                port: 80
            resources:
              requests:
                cpu: 1
                memoryInGB: 1
        replicaCount: 1
        networkRefs:
          - name: FabricServiceNetworkName