application:
  schemaVersion: 1.0.0
  name: ApplicationName
  properties:  
    services:
      - name: FabricServiceName
        properties:
          description: FabricServiceName description.
          osType: OsTypeValue
          codePackages:
            - name: FabricServiceName
              image: FabricServiceImage
              endpoints:
                - name: FabricServiceListener
                  port: FabricServicePort
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: FabricServiceNetworkName            